# Q1
### Write a NumPy program to create an array with the values 1, 7, 13, 105 and determine the size of the memory occupied by the array.


In [1]:
import numpy as np

In [5]:
def fun():
    a=np.array([1,7,13,105])
    print(f"Size:{a.size}")
fun()

Size:4


# Q2 
### Write a NumPy program to create an element-wise comparison (greater,    greater_equal, less and less_equal) of two given arrays.

In [11]:
  a1 = np.array([1, 2, 3])
print(a1 < 30) # [ True True False False False]
print(a1 > 30) # [False False False True True]
print(a1 <= 30) # [ True True True False False]
print(a1 >= 30) # [False False True True True]print(a1 == 30) # [False False True False False]
print(a1 != 30) # [ True True False True True]

[ True  True  True]
[False False False]
[ True  True  True]
[False False False]
[ True  True  True]


# Q3
### Write a NumPy program to create an array of 10 zeros, 10 ones, 10    fives, 10 tens, 10 twentys and 10 fiftys.

In [14]:

arr1=np.zeros(10,dtype=np.int8)
print(arr1)
arr=np.ones(10,dtype=np.int8)  #print 5 time 1
print(arr)
arr2=np.ones(10)*5
print(arr2)
arr3=np.ones(10)*10
print(arr3)
arr4=np.ones(10)*12
print(arr4)
arr5=np.ones(10)*15
print(arr5)


[0 0 0 0 0 0 0 0 0 0]
[1 1 1 1 1 1 1 1 1 1]
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
[10. 10. 10. 10. 10. 10. 10. 10. 10. 10.]
[12. 12. 12. 12. 12. 12. 12. 12. 12. 12.]
[15. 15. 15. 15. 15. 15. 15. 15. 15. 15.]


# Q4
### Write a NumPy program to create an array of integers from 30 to 70.

In [16]:
arr=np.arange(30,70)
print(arr)


[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69]


# Q5

In [17]:
arr=np.arange(50,95)
print(arr)


[50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73
 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94]


# Q6
### Write a NumPy program to create an array of all even integers from 20 to 80.

In [19]:
arr1=np.arange(20,80,2)
print(arr1)

[20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66
 68 70 72 74 76 78]


# Q7
### Write a NumPy program to create an array of all odd integers from 20 to 80.

In [23]:
arr1=np.arange(21,80,2)
print(arr1)

[21 23 25 27 29 31 33 35 37 39 41 43 45 47 49 51 53 55 57 59 61 63 65 67
 69 71 73 75 77 79]


# Q8
### Write a NumPy program to generate an array of 15 random numbers from 10    to 40.

In [25]:
a2 = np.random.randint(10, 40, 15)
print(a2)

[18 22 27 37 31 19 28 32 25 30 28 35 30 18 23]


# Q9
### Write a NumPy program to generate an array of 10 random numbers from 30    to 50.



In [27]:
a2 = np.random.randint(30, 50, 10)
print(a2)

[40 41 31 34 38 39 39 38 45 41]


# Q10
### Write a NumPy program to generate an array of 20 random numbers from 50    to 90.


In [28]:
a2 = np.random.randint(50, 90, 20)
print(a2)

[56 69 62 80 81 52 89 63 68 79 61 87 70 51 75 82 52 78 51 69]


# Q11
### Create any two arrays & perform various mathematical operations.
    i.e. Addition, Substraction, Multiplication, Divide.


In [30]:
a1 = np.array([11, 22,48, 33,44,55,66])
a2 = np.array([10, 20, 33,40,50,70,60])
print(a1 + a2) 
print(a1 - a2) 
# print(a1 / a2)
print(a1 // a2) 
print(a1 * a2) 

[ 21  42  81  73  94 125 126]
[  1   2  15  -7  -6 -15   6]
[1 1 1 0 0 0 1]
[ 110  440 1584 1320 2200 3850 3960]


# Q12
### Write a NumPy program to create a 3x4 matrix filled with values from 10 to 21.

In [31]:
m = np.arange(10, 22).reshape((3, 4))
print(m)


[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]


# Q13
### Write a NumPy program to create a 3x3 identity matrix, i.e. the diagonal     elements are 1, the rest are 0.

In [32]:
x = np.eye(3)
print(x)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


# Q14
### Write a NumPy program to find the number of rows and columns in a given     matrix. 

In [37]:
n=np.array([[1,2,4],[7,77 ,777]])
matrix=n.shape
rows,columns =matrix
print(f"rows={rows} columns={columns}")

rows=2 columns=3


# Q15
### Write a NumPy program to create a 5x5 zero matrix with elements on the     main diagonal equal to 1, 2, 3, 4, 5.

In [40]:
x = np.diag([1,2,3,4,5])
print(x)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


# Q16
### Write a NumPy program to create a 3x3x3 array filled with arbitrary values.

In [42]:
a= np.random.random((3,3,3))
print(a)

[[[0.15232766 0.17430633 0.7630974 ]
  [0.72728123 0.91974463 0.87107598]
  [0.74695727 0.31528024 0.38801436]]

 [[0.74338932 0.92039    0.72821927]
  [0.81355748 0.39150741 0.18147673]
  [0.99390882 0.06002873 0.9640774 ]]

 [[0.33178339 0.34859469 0.11633774]
  [0.05402416 0.92551873 0.01806057]
  [0.51372118 0.97191289 0.13005992]]]


# Q17 
### Write a NumPy program to create a 2x3x4 array filled with arbitrary values.

In [43]:
a=np.random.random((2,3,4))
print(a)

[[[0.30187542 0.03642039 0.89358182 0.77239472]
  [0.18218905 0.80166643 0.45927298 0.68316565]
  [0.68964505 0.87560467 0.47481338 0.02658442]]

 [[0.77680838 0.93935556 0.26913646 0.35041194]
  [0.21335834 0.85882958 0.14184959 0.15691524]
  [0.52488806 0.62660548 0.5349441  0.20893179]]]


# Q18
### Write a NumPy program to convert a list of numeric values into a one-    dimensional NumPy array.

In [45]:
l=[11.2,552,8,44.5,45]
print("NUmerical value:",l)
a=np.array(l)
print(f"One- dimensional NumPy array:{a}")

NUmerical value: [11.2, 552, 8, 44.5, 45]
One- dimensional NumPy array:[ 11.2 552.    8.   44.5  45. ]


# Q19
### Write a NumPy program to create a 3x3 matrix with values ranging from 2 to 10.

In [46]:
x = np.arange(2, 11).reshape(3, 3)
print(x)


[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


# Q20
### Write a NumPy program to create an array with values ranging from 12 to 38.

In [50]:
xx = np.arange(12, 38)
print(xx)


[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]


# Q21
### Write a NumPy program to reverse an array (the first element becomes the last).

In [51]:
a=np.array([11,22,33,44,55])
print(a)
a=a[::-1]
print(a)

[11 22 33 44 55]
[55 44 33 22 11]


# Q22
### Write a NumPy program to convert an data type into to a floating type.

In [62]:
a=np.array([11,22,33,44,55])
print(a)
a=a.astype(float)
print(b)

[11 22 33 44 55]
[11. 22. 33. 44. 55.]


# Q23
### Write a NumPy program to convert a list array.